name: Manage outdated dependencies and create issue

on: 
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  check-outdated-dependencies:
    runs-on: macos-latest
    name: Check outdated dependencies and create issue if it doesn't exist
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Check outdated dependencies and create issue
        id: check-outdated-dependencies-and-create-issue
        uses: rudderlabs/github-action-updated-dependencies-notifier@main
        with:
          outdated-dependency-names: "com.userleap:userleap-android-sdk"
          directory: "sprig/build.gradle"
          title: "fix: update Sprig SDK to the latest version"
          labels: "outdatedDependency"
          color: "FBCA04"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get the github issue url
        if: steps.check-outdated-dependencies-and-create-issue.outputs.issue-url != ''
        run: echo "The Github issue url is ${{ steps.check-outdated-dependencies-and-create-issue.outputs.issue-url }}"
